### ISSUE TITLE
Output auc table contains fewer samples than number of mzXML files in the input directory

### ISSUE THREAD

**Issue by beatapomian** [pablovgd/TARDIS#12]
There is a mismatch between the number of mzXML files  and the number of samples in the output table.

**Comment by pablovgd** [comment]
Hi Beata,

Thanks for reporting. I'll take a look at the files you send, but my best guess is that currently, files/samples that return NA for every compound in the target list, are not listed in the output. I'll update this in the code so that they are kept in the output with all NA's.

**Comment by pablovgd** [comment]
It turned out that in my current code, when the `max_intensity_filter` was `= 0` it was still filtering out samples that have only `NA` for all compounds. For now, this has been resolved by disabling the filter if `max_intensity_filter = 0`. I'll resolve this and push to main. So, be aware that setting the `max_int_filter` to anything else than 0, will also remove `NA`.
